code --install-extension anthropic.claude-code
code --install-extension bierner.markdown-mermaid
code --install-extension cssho.vscode-svgviewer
code --install-extension docker.docker
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-pull-request-github
code --install-extension graphql.vscode-graphql
code --install-extension graphql.vscode-graphql-syntax
code --install-extension hashicorp.terraform
code --install-extension ms-python.python
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension nomicfoundation.hardhat-solidity
code --install-extension redhat.vscode-yaml
code --install-extension sourcegraph.amp
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension styled-components.vscode-styled-components
code --install-extension synapsevscode.synapse
code --install-extension tamasfe.even-better-toml
code --install-extension unifiedjs.vscode-mdx
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wmaurer.change-case
code --install-extension zhuangtongfa.material-theme
